In [1]:
import torch
import numpy as np

In [2]:
x = torch.ones(3)
rnd = torch.randn(3)

In [3]:
np_vector = np.array([1, 2, 3])
y = torch.from_numpy(np_vector).float()

In [4]:
x.requires_grad_(True)
y.requires_grad_(True)

tensor([1., 2., 3.], requires_grad=True)

In [5]:
z1 = x * rnd
z2 = z1 + torch.log(y) + x

In [6]:
print(z1, z2)

tensor([-1.1235,  0.4010, -0.9064], grad_fn=<ThMulBackward>) tensor([-0.1235,  2.0941,  1.1922], grad_fn=<ThAddBackward>)


In [7]:
sum_z2 = torch.sum(z2)

In [22]:
sum_z2.backward()
print(x.grad, y.grad)

tensor([ 1.8946,  1.3821, -0.0438]) tensor([1.0000, 0.5000, 0.3333])


In [23]:
tmp = x.clone()
while tmp.norm() < 10:
    print(tmp)
    tmp *= 1.1

tensor([1., 1., 1.], grad_fn=<CloneBackward>)
tensor([1.1000, 1.1000, 1.1000], grad_fn=<MulBackward>)
tensor([1.2100, 1.2100, 1.2100], grad_fn=<MulBackward>)
tensor([1.3310, 1.3310, 1.3310], grad_fn=<MulBackward>)
tensor([1.4641, 1.4641, 1.4641], grad_fn=<MulBackward>)
tensor([1.6105, 1.6105, 1.6105], grad_fn=<MulBackward>)
tensor([1.7716, 1.7716, 1.7716], grad_fn=<MulBackward>)
tensor([1.9487, 1.9487, 1.9487], grad_fn=<MulBackward>)
tensor([2.1436, 2.1436, 2.1436], grad_fn=<MulBackward>)
tensor([2.3579, 2.3579, 2.3579], grad_fn=<MulBackward>)
tensor([2.5937, 2.5937, 2.5937], grad_fn=<MulBackward>)
tensor([2.8531, 2.8531, 2.8531], grad_fn=<MulBackward>)
tensor([3.1384, 3.1384, 3.1384], grad_fn=<MulBackward>)
tensor([3.4523, 3.4523, 3.4523], grad_fn=<MulBackward>)
tensor([3.7975, 3.7975, 3.7975], grad_fn=<MulBackward>)
tensor([4.1772, 4.1772, 4.1772], grad_fn=<MulBackward>)
tensor([4.5950, 4.5950, 4.5950], grad_fn=<MulBackward>)
tensor([5.0545, 5.0545, 5.0545], grad_fn=<MulBackward>)
te